name = "Diggerpack 2"
author = "ubkh"
version = "2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "427dfbb3176e21efd8a51e297241618a843b4f27a404d8d4e41399729dbc1dd3"

[versions]
forge = "47.4.8"
minecraft = "1.20.1"
