name = "Diggerpack 2"
author = "ubkh"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3bdba37d47179ab344b8ce91ae608ba9ef89831962b3794b2a82a90b4ae85ab4"

[versions]
forge = "47.4.8"
minecraft = "1.20.1"
