name = "Diggerpack 2"
author = "ubkh"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27114076057e9f1a5b4530a8caf5a9a4c52feff12b35c3d3632013bd68037651"

[versions]
forge = "47.4.8"
minecraft = "1.20.1"
