config-version = 1
fade-time = 0.39816497093023195
mod-enabled = true
animation-curve = 0
fade-type = 0
fade-enabled = true
animation-enabled = false
animation-offset = 64.0
show-mod-button-in-settings = true
animate-near-player = true
update-notifier-enabled = false
animation-time = 2.56
