
["Dementia config"]
	#Minimun cooldown before things go missing 
	MIN_COOLDOWN = 60
	#Maximum cooldown before things go missing
	MAX_COOLDOWN = 300
	#Maximum items count to missing
	MAX_COUNT = 3
	#Chance to teleport player in random point within one hundred blocks
	TP_CHANCE = 20
	#Chance to set the effect of hunger to the player
	HUNGER_CHANCE = 20

