#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Oct 16 20:49:39 BST 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
