#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Nov 07 14:13:15 GMT 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
