#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Sep 29 18:36:32 BST 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
